# Generated by Django 4.0.5 on 2022-07-08 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_customeruser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomerUser',
        ),
    ]
