# Generated by Django 4.0.5 on 2022-09-09 01:44

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_alter_message_from_user_alter_message_room_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='room_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='message',
            name='room',
            field=models.ForeignKey(blank=True, default=7, on_delete=django.db.models.deletion.CASCADE, related_name='room_messages', to='blog.room'),
        ),
        migrations.AlterField(
            model_name='message',
            name='sent_datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 8, 21, 44, 52, 205946)),
        ),
    ]
