# Generated by Django 4.0.5 on 2022-09-09 01:57

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_message_room_name_alter_message_room_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_messages', to='blog.room'),
        ),
        migrations.AlterField(
            model_name='message',
            name='sent_datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 8, 21, 57, 2, 670080)),
        ),
    ]
