# Generated by Django 4.0.5 on 2022-09-09 02:27

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_alter_message_room_alter_message_sent_datetime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='from_user',
        ),
        migrations.AlterField(
            model_name='message',
            name='room',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='room_messages', to='blog.room'),
        ),
        migrations.AlterField(
            model_name='message',
            name='sent_datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 8, 22, 27, 30, 280932)),
        ),
    ]
