# Generated by Django 4.0.5 on 2022-09-11 16:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_remove_message_from_user_alter_message_room_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='sent_datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 11, 12, 37, 50, 506072)),
        ),
    ]
