# Generated by Django 4.0.5 on 2022-09-29 00:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_alter_message_sent_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='sent_datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 28, 20, 33, 51, 437611)),
        ),
    ]
